//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.15 at 09:59:19 AM ICT 
//


package com.zygen.etax.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zygen.etax.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SignPdfResponseKey_QNAME = new QName("http://model.etax.zygen.com/", "key");
    private final static QName _SignPdfResponseSignPdfResult_QNAME = new QName("http://model.etax.zygen.com/", "SignPdfResult");
    private final static QName _SignXmlRequestXmlContent_QNAME = new QName("http://model.etax.zygen.com/", "XmlContent");
    private final static QName _SignXmlResponseSignXmlResult_QNAME = new QName("http://model.etax.zygen.com/", "SignXmlResult");
    private final static QName _SignPdfRequestPdfBase64_QNAME = new QName("http://model.etax.zygen.com/", "PdfBase64");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zygen.etax.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SignXmlResponse }
     * 
     */
    public SignXmlResponse createSignXmlResponse() {
        return new SignXmlResponse();
    }

    /**
     * Create an instance of {@link SignPdfResponse }
     * 
     */
    public SignPdfResponse createSignPdfResponse() {
        return new SignPdfResponse();
    }

    /**
     * Create an instance of {@link SignXmlRequest }
     * 
     */
    public SignXmlRequest createSignXmlRequest() {
        return new SignXmlRequest();
    }

    /**
     * Create an instance of {@link SignPdfRequest }
     * 
     */
    public SignPdfRequest createSignPdfRequest() {
        return new SignPdfRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "key", scope = SignPdfResponse.class)
    public JAXBElement<String> createSignPdfResponseKey(String value) {
        return new JAXBElement<String>(_SignPdfResponseKey_QNAME, String.class, SignPdfResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "SignPdfResult", scope = SignPdfResponse.class)
    public JAXBElement<String> createSignPdfResponseSignPdfResult(String value) {
        return new JAXBElement<String>(_SignPdfResponseSignPdfResult_QNAME, String.class, SignPdfResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "key", scope = SignXmlRequest.class)
    public JAXBElement<String> createSignXmlRequestKey(String value) {
        return new JAXBElement<String>(_SignPdfResponseKey_QNAME, String.class, SignXmlRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "XmlContent", scope = SignXmlRequest.class)
    public JAXBElement<String> createSignXmlRequestXmlContent(String value) {
        return new JAXBElement<String>(_SignXmlRequestXmlContent_QNAME, String.class, SignXmlRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "key", scope = SignXmlResponse.class)
    public JAXBElement<String> createSignXmlResponseKey(String value) {
        return new JAXBElement<String>(_SignPdfResponseKey_QNAME, String.class, SignXmlResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "SignXmlResult", scope = SignXmlResponse.class)
    public JAXBElement<String> createSignXmlResponseSignXmlResult(String value) {
        return new JAXBElement<String>(_SignXmlResponseSignXmlResult_QNAME, String.class, SignXmlResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "key", scope = SignPdfRequest.class)
    public JAXBElement<String> createSignPdfRequestKey(String value) {
        return new JAXBElement<String>(_SignPdfResponseKey_QNAME, String.class, SignPdfRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "PdfBase64", scope = SignPdfRequest.class)
    public JAXBElement<String> createSignPdfRequestPdfBase64(String value) {
        return new JAXBElement<String>(_SignPdfRequestPdfBase64_QNAME, String.class, SignPdfRequest.class, value);
    }

}
