//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.08 at 02:22:11 PM ICT 
//


package com.zygen.etax.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zygen.etax.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SignXmlModel_QNAME = new QName("http://model.etax.zygen.com/", "SignXmlModel");
    private final static QName _BaseModel_QNAME = new QName("http://model.etax.zygen.com/", "BaseModel");
    private final static QName _SignPdfModel_QNAME = new QName("http://model.etax.zygen.com/", "SignPdfModel");
    private final static QName _SignXmlResponseSignXmlResult_QNAME = new QName("http://model.etax.zygen.com/", "SignXmlResult");
    private final static QName _SignXmlModelSignedXml_QNAME = new QName("http://model.etax.zygen.com/", "SignedXml");
    private final static QName _BaseModelRespName_QNAME = new QName("http://model.etax.zygen.com/", "RespName");
    private final static QName _SignPdfResponseSignPdfResult_QNAME = new QName("http://model.etax.zygen.com/", "SignPdfResult");
    private final static QName _SignPdfModelSignedPdf_QNAME = new QName("http://model.etax.zygen.com/", "SignedPdf");
    private final static QName _SignXmlRequestSigningConfigName_QNAME = new QName("http://model.etax.zygen.com/", "SigningConfigName");
    private final static QName _SignXmlRequestXmlContent_QNAME = new QName("http://model.etax.zygen.com/", "XmlContent");
    private final static QName _SignPdfRequestPdfBase64_QNAME = new QName("http://model.etax.zygen.com/", "PdfBase64");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zygen.etax.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SignXmlResponse }
     * 
     */
    public SignXmlResponse createSignXmlResponse() {
        return new SignXmlResponse();
    }

    /**
     * Create an instance of {@link SignXmlModel }
     * 
     */
    public SignXmlModel createSignXmlModel() {
        return new SignXmlModel();
    }

    /**
     * Create an instance of {@link SignPdfModel }
     * 
     */
    public SignPdfModel createSignPdfModel() {
        return new SignPdfModel();
    }

    /**
     * Create an instance of {@link SignPdfResponse }
     * 
     */
    public SignPdfResponse createSignPdfResponse() {
        return new SignPdfResponse();
    }

    /**
     * Create an instance of {@link BaseModel }
     * 
     */
    public BaseModel createBaseModel() {
        return new BaseModel();
    }

    /**
     * Create an instance of {@link SignXmlRequest }
     * 
     */
    public SignXmlRequest createSignXmlRequest() {
        return new SignXmlRequest();
    }

    /**
     * Create an instance of {@link SignPdfRequest }
     * 
     */
    public SignPdfRequest createSignPdfRequest() {
        return new SignPdfRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignXmlModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "SignXmlModel")
    public JAXBElement<SignXmlModel> createSignXmlModel(SignXmlModel value) {
        return new JAXBElement<SignXmlModel>(_SignXmlModel_QNAME, SignXmlModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "BaseModel")
    public JAXBElement<BaseModel> createBaseModel(BaseModel value) {
        return new JAXBElement<BaseModel>(_BaseModel_QNAME, BaseModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignPdfModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "SignPdfModel")
    public JAXBElement<SignPdfModel> createSignPdfModel(SignPdfModel value) {
        return new JAXBElement<SignPdfModel>(_SignPdfModel_QNAME, SignPdfModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignXmlModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "SignXmlResult", scope = SignXmlResponse.class)
    public JAXBElement<SignXmlModel> createSignXmlResponseSignXmlResult(SignXmlModel value) {
        return new JAXBElement<SignXmlModel>(_SignXmlResponseSignXmlResult_QNAME, SignXmlModel.class, SignXmlResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "SignedXml", scope = SignXmlModel.class)
    public JAXBElement<String> createSignXmlModelSignedXml(String value) {
        return new JAXBElement<String>(_SignXmlModelSignedXml_QNAME, String.class, SignXmlModel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "RespName", scope = BaseModel.class)
    public JAXBElement<String> createBaseModelRespName(String value) {
        return new JAXBElement<String>(_BaseModelRespName_QNAME, String.class, BaseModel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignPdfModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "SignPdfResult", scope = SignPdfResponse.class)
    public JAXBElement<SignPdfModel> createSignPdfResponseSignPdfResult(SignPdfModel value) {
        return new JAXBElement<SignPdfModel>(_SignPdfResponseSignPdfResult_QNAME, SignPdfModel.class, SignPdfResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "SignedPdf", scope = SignPdfModel.class)
    public JAXBElement<String> createSignPdfModelSignedPdf(String value) {
        return new JAXBElement<String>(_SignPdfModelSignedPdf_QNAME, String.class, SignPdfModel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "SigningConfigName", scope = SignXmlRequest.class)
    public JAXBElement<String> createSignXmlRequestSigningConfigName(String value) {
        return new JAXBElement<String>(_SignXmlRequestSigningConfigName_QNAME, String.class, SignXmlRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "XmlContent", scope = SignXmlRequest.class)
    public JAXBElement<String> createSignXmlRequestXmlContent(String value) {
        return new JAXBElement<String>(_SignXmlRequestXmlContent_QNAME, String.class, SignXmlRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "SigningConfigName", scope = SignPdfRequest.class)
    public JAXBElement<String> createSignPdfRequestSigningConfigName(String value) {
        return new JAXBElement<String>(_SignXmlRequestSigningConfigName_QNAME, String.class, SignPdfRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.etax.zygen.com/", name = "PdfBase64", scope = SignPdfRequest.class)
    public JAXBElement<String> createSignPdfRequestPdfBase64(String value) {
        return new JAXBElement<String>(_SignPdfRequestPdfBase64_QNAME, String.class, SignPdfRequest.class, value);
    }

}
